name: Tag snake case verification

on:
  pull_request:
    
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './backend/go.mod'
          cache-dependency-path: './backend/go.sum'

      - name: Run lint
        run: go run ./cmd/checktags
        working-directory: ./backend
